"""rename field

Revision ID: 007078d0ce44
Revises: f1ebe9c5dea6
Create Date: 2025-06-30 12:35:01.178160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007078d0ce44'
down_revision: Union[str, Sequence[str], None] = 'f1ebe9c5dea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('original_body', sa.String(), nullable=True))
    op.drop_column('sms_data', 'raw_body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('raw_body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('sms_data', 'original_body')
    # ### end Alembic commands ###
