"""sms_data table update

Revision ID: 80b70406bdea
Revises: f1a93be77048
Create Date: 2025-06-22 01:14:04.836666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80b70406bdea'
down_revision: Union[str, Sequence[str], None] = 'f1a93be77048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_data_msg_id'), table_name='sms_data')
    op.drop_column('sms_data', 'msg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('msg_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sms_data_msg_id'), 'sms_data', ['msg_id'], unique=False)
    # ### end Alembic commands ###
