"""sms_data table

Revision ID: ab372595639c
Revises: 
Create Date: 2025-06-22 00:48:14.368559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab372595639c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_key', sa.String(), nullable=False),
    sa.Column('original_body', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('card', sa.String(length=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('txn_type', sa.String(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_key')
    )
    op.create_index('idx_sms_datetime', 'sms_data', ['datetime'], unique=False)
    op.create_index('idx_sms_sender', 'sms_data', ['sender'], unique=False)
    op.create_index('idx_sms_txn_type', 'sms_data', ['txn_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sms_txn_type', table_name='sms_data')
    op.drop_index('idx_sms_sender', table_name='sms_data')
    op.drop_index('idx_sms_datetime', table_name='sms_data')
    op.drop_table('sms_data')
    # ### end Alembic commands ###
