"""rename field

Revision ID: dcbadcb88d59
Revises: 007078d0ce44
Create Date: 2025-06-30 12:37:41.994643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcbadcb88d59'
down_revision: Union[str, Sequence[str], None] = '007078d0ce44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('datetime', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_sms_datetime'), table_name='sms_data')
    op.create_index('idx_sms_datetime', 'sms_data', ['datetime'], unique=False)
    op.drop_column('sms_data', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('idx_sms_datetime', table_name='sms_data')
    op.create_index(op.f('idx_sms_datetime'), 'sms_data', ['date'], unique=False)
    op.drop_column('sms_data', 'datetime')
    # ### end Alembic commands ###
