"""sms_data table update

Revision ID: f1a93be77048
Revises: ab372595639c
Create Date: 2025-06-22 01:10:05.538519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1a93be77048'
down_revision: Union[str, Sequence[str], None] = 'ab372595639c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('raw_body', sa.String(), nullable=False))
    op.add_column('sms_data', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sms_data', sa.Column('msg_id', sa.String(), nullable=True))
    op.add_column('sms_data', sa.Column('device_id', sa.String(), nullable=True))
    op.add_column('sms_data', sa.Column('parser_version', sa.String(), nullable=True))
    op.drop_index(op.f('idx_sms_datetime'), table_name='sms_data')
    op.create_index('idx_sms_datetime', 'sms_data', ['date'], unique=False)
    op.create_index(op.f('ix_sms_data_msg_id'), 'sms_data', ['msg_id'], unique=False)
    op.drop_column('sms_data', 'datetime')
    op.drop_column('sms_data', 'original_body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('original_body', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('sms_data', sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sms_data_msg_id'), table_name='sms_data')
    op.drop_index('idx_sms_datetime', table_name='sms_data')
    op.create_index(op.f('idx_sms_datetime'), 'sms_data', ['datetime'], unique=False)
    op.drop_column('sms_data', 'parser_version')
    op.drop_column('sms_data', 'device_id')
    op.drop_column('sms_data', 'msg_id')
    op.drop_column('sms_data', 'date')
    op.drop_column('sms_data', 'raw_body')
    # ### end Alembic commands ###
