"""rename field

Revision ID: f1ebe9c5dea6
Revises: 80b70406bdea
Create Date: 2025-06-30 12:27:49.442756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ebe9c5dea6'
down_revision: Union[str, Sequence[str], None] = '80b70406bdea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('msg_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('sms_data_original_key_key'), 'sms_data', type_='unique')
    op.create_unique_constraint(None, 'sms_data', ['msg_id'])
    op.drop_column('sms_data', 'original_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_data', sa.Column('original_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sms_data', type_='unique')
    op.create_unique_constraint(op.f('sms_data_original_key_key'), 'sms_data', ['original_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('sms_data', 'msg_id')
    # ### end Alembic commands ###
